### ISSUE TITLE
incorrect redirect

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-bxl#10]
I tested the page:
http://oca.scientologie-info.be/dk/
It is redirecting people to the wrong site/page
https://github.com/qualifiedleads/oca-bxl/compare/ba08694b2f...e949a458db#

The [BE page](http://oca.scientologie-info.be/be/) should redirect people to  https://www.oca.scientology.nl/questions.html

Instead it has been overwritten and now simply has a default redirect to 
https://www.oxfordcapacityanalysis.org/questions.html

This is incorrect language and incorrect location

About Location, see following:
on-submit an "orgid" param is passed, eg:
https://github.com/qualifiedleads/oca-bxl/blob/e949a458db54ca5ddcd24e6c89034f80f10e2335/be/index.html#L129

That tells the website at https://www.oxfordcapacityanalysis.org/questions.html which language and location the user is in.

List of "orgid"
cse = Belgium (dirs /be & /bxl-fr ) 
dkd = Denmark

**Comment by jenbrannstrom** [comment]
This page http://oca.scientologie-info.be/dk/
Should redirect to this question page in Danish language
https://www.oca.scientology.dk/questions.html?oca-started=1&
(Right now it's showing Dutch language.)

Also, webform data is NOT arriving in the G Sheet: https://docs.google.com/spreadsheets/d/1hnqsIGMrSrdetRoA7X_Z3SzA3A8pkwgbyXhe6ZtgIcY/edit#gid=1826500145

**Comment by sarcopter** [comment]
Hi! You must disable web app and deploy it again because you owner of sheet:

https://docs.google.com/spreadsheets/d/1hnqsIGMrSrdetRoA7X_Z3SzA3A8pkwgbyXhe6ZtgIcY/edit#gid=1826500145

Please deploy it with following params:

"Who has access to the app:" "Anyone, even anonymous"

**Comment by jenbrannstrom** [comment]
@sarcopter ok deployed

**Comment by sarcopter** [comment]
fixed

**Comment by jenbrannstrom** [comment]
excellent
