### ISSUE TITLE
BELGIUM page (Dutch version)

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-bxl#12]
Please clean up this dir, the same as you cleaned up DK.
Remove old files
add commenting

point to [this sheet:](https://docs.google.com/spreadsheets/d/1dZVeODXxg6VWnzw59NzFYK4pCBBWS8GhPXhbpJiRYQc/edit#gid=189891205)
Notify me when I need to Publish/deploy newly

The 'orgid' of this page is incorrect. It points to 'ams' - it should be 'cse'

**Comment by sarcopter** [comment]
ams to cse fixed
No re-Deploying needed
