### ISSUE TITLE
Denmark Page Fails

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-bxl#6]
Dear Raj,
Please can you fix this page:
https://github.com/qualifiedleads/oca-bxl/blob/gh-pages/dk/index.html
http://oca.scientologie-info.be/dk/

It doesn;t submit, just hangs on clicking "Start the Test"

**Comment by aviox-git** [comment]
@jenbrannstrom  Working on it

**Comment by aviox-git** [comment]
It is due to CORS error

![Screenshot from 2020-03-02 18-49-03](https://user-images.githubusercontent.com/47270302/75680090-c8bf3980-5cb6-11ea-84d4-372bb5e7cc26.png)

**Comment by jenbrannstrom** [comment]
Then why do the other pages work?
http://oca.scientologie-info.be/bxl-fr/ - PASSING
http://oca.scientologie-info.be/be/ - PASSING

**Comment by aviox-git** [comment]
I am checking why it is working for other pages and not for this one.

**Comment by jenbrannstrom** [comment]
nudge @aviox-git

**Comment by jenbrannstrom** [comment]
nudge @aviox-git

**Comment by aviox-git** [comment]
I have fixed the issue. Just doing some testings on local. After that will test on live. then update you accordingly. @jenbrannstrom

**Comment by jenbrannstrom** [comment]
Ok, but you seem to have added https://www.googletagmanager.com/gtag/js?id=AW-958901669 to EVERY page now.
I don't know what it was before, but I'm not sure if I have access to that Tag manager.

**Comment by aviox-git** [comment]
Yes I have added this script to every page which is not in working. Because it gives CORS error which is due to missing of this script form all files that are not working.

**Comment by priyankush-siloria** [comment]
@jenbrannstrom Please check and verify the issue is fixed
