### ISSUE TITLE
DK submissions sheet

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-bxl#8]
This page's webform: 
http://oca.scientologie-info.be/dk/
should submit to this G sheet
https://www.oca.scientology.dk/

**Comment by priyankush-siloria** [comment]
Please share the google sheet link and provide access to the sheet.

**Comment by jenbrannstrom** [comment]
https://docs.google.com/spreadsheets/d/1DnbPcqUYPFp5-GdfrKMlQXcgHzjHu16_wGJa63eTmhI/edit?pli=1#gid=1826500145

**Comment by jenbrannstrom** [comment]
@priyankush-siloria is it done?

**Comment by priyankush-siloria** [comment]
It seems to have permission errors. the script didn't have permissions. Provide script permission when you deploy it as a web app. This can only be done by the actual owner of sheet.
![Screenshot 2020-03-27 at 1 02 42 PM](https://user-images.githubusercontent.com/44189293/77732745-870e7e00-702b-11ea-8390-ceb1ddf4a1f5.png)
@jenbrannstrom

**Comment by jenbrannstrom** [comment]
I made a clone of the Sheet, clone of the script, published to Web
and opened to all users.
Still Fails.
Feel free to make a Gsheet yourself, and test it

**Comment by priyankush-siloria** [comment]
I have tested with my sheet and make it work. also put back your sheet link. Please verify the screenshot below in your settings. if it is not correct then fix it and deploy the script again.
![Screenshot 2020-03-28 at 3 06 27 AM](https://user-images.githubusercontent.com/44189293/77802848-c4155780-70a1-11ea-95db-5bb882c42360.png)

**Comment by priyankush-siloria** [comment]
@jenbrannstrom Please check and confirm on this

**Comment by jenbrannstrom** [comment]
@priyankush-siloria can you just fix it?

**Comment by priyankush-siloria** [comment]
I already fixed it. Also tested with my own google sheet it was working fine. There is no issue in the repo anymore. The issue is only at GSheet. Please recheck permission with the sheet.

**Comment by jenbrannstrom** [comment]
@priyankush-siloria 
It just hangs indefinitely , each time I click "publish as web app"
I will make a copy and use a new sheet URL.
Can you tell me which file it needs to be in? there are two JS files: 
oca_submit.js
&
onsubmit.js
Both contain the Sheet URL. Are they both used? Or is only one?

**Comment by aviox-git** [comment]
It is onsubmit.js but just in case just change link in both js files.

**Comment by jenbrannstrom** [comment]
> It is onsubmit.js but just in case just change link in both js files.

Can someone please go through the code and check, so we streamline it?

**Comment by jenbrannstrom** [comment]
I changed them both, but now it no longer submits at all.
The web app is deployed 
https://script.google.com/macros/s/AKfycby3orLGTOYXGXL82hyTMFHOMErIURpCJPIl76juVH1kuefgGWEu/exec

**Comment by aviox-git** [comment]
ok thank you. Give me sheet link too. So i can check

**Comment by aviox-git** [comment]
@jenbrannstrom  Try clearing you browser cache issue is JS is not refreshing. Updated JS code is not loading.

**Comment by jenbrannstrom** [comment]
https://docs.google.com/spreadsheets/d/1hnqsIGMrSrdetRoA7X_Z3SzA3A8pkwgbyXhe6ZtgIcY/edit#gid=1826500145

**Comment by aviox-git** [comment]
I have done testing it is working. Issuse with JS cache on browser. @jenbrannstrom 
![Screenshot 2020-04-01 at 6 03 21 AM](https://user-images.githubusercontent.com/47270302/78144975-f3371a80-744d-11ea-991a-b0bf8e36273a.png)

**Comment by jenbrannstrom** [comment]
I see that , but it redirects to the wrong page

**Comment by aviox-git** [comment]
ok which page it needs to redirect?

**Comment by jenbrannstrom** [comment]
the 200 questions - like always

**Comment by aviox-git** [comment]
ohk let me check

**Comment by jenbrannstrom** [comment]
@aviox-git any update?

**Comment by aviox-git** [comment]
working on it. Just give me some more time will update you ASAP.

**Comment by aviox-git** [comment]
https://www.oxfordcapacityanalysis.org/
do we have git for this?

**Comment by jenbrannstrom** [comment]
no, it's not ours
But several of the other pages do work correctly.
Maybe find what the DIFF is between them

**Comment by aviox-git** [comment]
ok

**Comment by aviox-git** [comment]
This is done.

**Comment by jenbrannstrom** [comment]
you're kidding right?
It goes straight to the final page, skipping 200 questions
https://i.imgur.com/VyUybFx.jpg

**Comment by aviox-git** [comment]
It works properly at my end, may be the issue in your browser. Maybe you have already completed the test and it is stored in the cache.
I am sending you screenshare at my end.
https://drive.google.com/file/d/1P3G-odcizmExIM6XuHwXDrZCtu106WGG/view
