### ISSUE TITLE
BE page fails

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/oca-bxl#9]
@rajinder-mohan 
This page 
https://github.com/qualifiedleads/oca-bxl/blob/gh-pages/be/index.html
has the Same issue as #8 

visible at: http://oca.scientologie-info.be/be/

The details need to be:
1. submitted to G Sheet
2. Sent on to the API of oxfordcapacityalysis, and user redirected to the 200 questions there

**Comment by aviox-git** [comment]
I think it is ls due to sheet issues. So first please fix the sheet then we will check if the issue still remains.
